import mongoose from "mongoose";

const candidateSchema = new mongoose.Schema(
  {
    job: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Job",
      required: true,
      index: true,
    },

    fileName: {
      type: String,
      required: true,
    },

    candidateName: {
      type: String,
      default: "Unnamed Candidate",
    },

    // Full extracted text from the uploaded PDF
    resumeText: {
      type: String,
      required: true,
    },

    // Structured information extracted by Gemini
    extracted: {
      skills: {
        type: [String],
        default: [],
      },

      experience: {
        type: [
          {
            role: { type: String, default: "" },
            company: { type: String, default: "" },
            duration: { type: String, default: "" },
          },
        ],
        default: [],
      },

      education: {
        type: [
          {
            degree: { type: String, default: "" },
            institution: { type: String, default: "" },
            year: { type: String, default: "" },
          },
        ],
        default: [],
      },
    },

    // LLM screening result
    matchScore: {
      type: Number,
      min: 0,
      max: 10,
      default: 0,
    },

    // Complete reasoning generated according to the user's prompt
    justification: {
      type: String,
      default: "",
    },

    // Specific improvements generated by the LLM
    suggestions: {
      type: [String],
      default: [],
    },

    // Optional structured screening output
    screening: {
      requirementMatch: {
        type: String,
        default: "",
      },

      strongMatches: {
        type: [String],
        default: [],
      },

      majorGaps: {
        type: [String],
        default: [],
      },

      recommendation: {
        type: String,
        default: "",
      },
    },

    // Store the prompt used for this screening
    promptUsed: {
      type: String,
      default: "",
    },

    status: {
      type: String,
      enum: ["processing", "completed", "failed"],
      default: "processing",
    },

    error: {
      type: String,
      default: "",
    },
  },
  {
    timestamps: true,
  }
);

export default mongoose.model("Candidate", candidateSchema);